export interface ICargo {

    id: number,
    shipCode: number,
    voy: number,
    seqNo: number,
    fixNo: number,
    fixCargoNo: string,
    chartererCode: string,
    charterer: string,
    quantity: number,
    quantityTt: string,
    commodity: string,
    loadPort: string,
    dischPort: string,
    rateTt: string,
    CommOnDem: number,
    freightHire: number,
    commission: number,
    demurrage?: string,
    ballBonus?: string,
    bunkerComp?: string,
    UPDC: number,
    COASpot: string,
    brokerCode1?: string,
    brokerCode2?: string,
    brokerComm1?: number,
}
  